server:
  servlet:
    context-path: /
  port: 12139

logging:
  level:
    root: info

spring:
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
    serialization:
      indent_output: true
      fail_on_empty_beans: false
    defaultPropertyInclusion: NON_EMPTY
    deserialization:
      fail_on_unknown_properties: false
    parser:
      allow_unquoted_control_chars: true
      allow_single_quotes: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/yun?serverTimezone=UTC&useUnicode=true&characterencoding=utf8
      username: root
      password: root
      initial-size: 5
      max-active: 30
      min-idle: 5
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true

      max-pool-prepared-statement-per-connection-size: 50
      filters: stat,wall,log4j2
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      useGlobalDataSourceStat: true
      stat-view-servlet:
        login-username: admin
        login-password: admin
  thymeleaf:
    encoding: UTF-8
    mode: HTML
    cache: false
    prefix: classpath:/templates/*


mybatis:
  type-aliases-package: com.aistar.pojo
  mapper-locations: classpath:com/aistar/mapper/*Mapper.xml


pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql




